### ISSUE TITLE
v0.4 Issue - nxm url handling not working on SteamDeck

### ISSUE THREAD

**Issue by MaggiWuerze** [Nexus-Mods/NexusMods.App#1134] opened 2024-03-26 14:10 UTC
# Bug Report

## Summary
The NMA does not handle `nxm://` links like it is supposed to. The `nexusmods-app-nxm.desktop` file is present but when I try to open a vortex link on Nexus it instead opens the `KDG Open` App, which prompts me to select an Application to handle the link. The `nexusmods-app-nxm.desktop` file is not listed there as a possible handler. This happens in Firefox as well as Chromium.

Firefox allows me to manually choose the `nexusmods-app-nxm.desktop` file, but that does not work either.

## Steps to reproduce
Try to click a vortex link on NexusMods

## What is the expected behaviour?
The NMA handling the link

**Comment by Sewer56** [comment] 2024-03-26 14:16
IIRC this was one of the things that broke with the recent multiwindow PR

**Comment by MaggiWuerze** [comment] 2024-03-26 14:53
Could it be related to whether I run it as an AppImage or through the zipped release?

**Comment by MattSturgeon** [comment] 2024-03-29 05:06
The template's `MimeType` is blank.

It should be:

```
MimeType=x-scheme-handler/nxm;x-scheme-handler/nxm-protocol
```

Also note, the `Exec` command should have a `%u` (which will be replaced with the actual URL)

**Comment by erri120** [comment] 2024-03-29 11:10
> The [template](https://github.com/Nexus-Mods/NexusMods.App/blob/51fb1bd09e722dfcd804767cab35addbf3f83f92/src/NexusMods.App/app.desktop)'s `MimeType` is blank.
> 
> It should be:
> 
> ```
> MimeType=x-scheme-handler/nxm;x-scheme-handler/nxm-protocol
> ```
> 
> Also note, the `Exec` command should have a `%u` (which will be replaced with the actual URL)

The desktop file you're linking is for the Application itself. We generate a separate desktop file for the URL itself at runtime:

https://github.com/Nexus-Mods/NexusMods.App/blob/51fb1bd09e722dfcd804767cab35addbf3f83f92/src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs#L44-L70

**Comment by erri120** [comment] 2024-03-29 11:11
The NXM handler works fine on my machine, and we've tested it on a Steam Deck before without issues @halgari.

**Comment by MattSturgeon** [comment] 2024-03-29 13:52
> We generate a separate desktop file for the URL itself at runtime

Interesting. I assume this is done so that the mimetype association can be toggled via app settings?

Just a heads up, this will likely run into sandboxing issues if the app is ever packaged as a flatpak (or similar).

IIRC there's an xdg desktop portal for creating desktop entry files

**Comment by erri120** [comment] 2024-04-02 11:49
> Could it be related to whether I run it as an AppImage or through the zipped release?

If you used the AppImage version, then this issue is a duplicate of #1149. I'm also fixing #1150 in #1152.

**Comment by MaggiWuerze** [comment] 2024-04-02 14:22
@erri120 More like a regression than a duplicate I would say, since the other was closed (after being fixed I suppose)

**Comment by erri120** [comment] 2024-04-02 14:45
> @erri120 More like a regression than a duplicate I would say, since the other was closed (after being fixed I suppose)

Can you elaborate what issues you're referencing? I fixed both #1149 and #1150 with #1152.

**Comment by MaggiWuerze** [comment] 2024-04-03 07:02
Ah, I didn't check the dates. Thought they were fixed some time ago. I will try the latest build, but can already say, that the 0.4 release did not fix the issue for me

**Comment by TigerBeanst** [comment] 2024-04-05 22:58
Do you use pikdum/steam-deck before?

**Comment by MaggiWuerze** [comment] 2024-04-08 10:50
No, never used that

**Comment by MaggiWuerze** [comment] 2024-04-08 14:07
Ok, so I've tried [GitBuild 224](https://github.com/Nexus-Mods/NexusMods.App/actions/runs/8596915092) and when I click on a nxm link it just opens a new instance of the app without handling the link

**Comment by erri120** [comment] 2024-04-08 14:14
@MaggiWuerze can you send some logs? `~/.local/state/NexusMods.App/Logs`

**Comment by erri120** [comment] 2024-04-16 11:19
@MaggiWuerze did you try one of the latest builds? https://github.com/Nexus-Mods/NexusMods.App/actions/workflows/git-builds.yaml

**Comment by MaggiWuerze** [comment] 2024-04-16 13:02
That was with the Build#224, I can try a more recent one if you want

**Comment by erri120** [comment] 2024-04-16 13:19
> That was with the Build#224, I can try a more recent one if you want

Try one of the recent builds. They have more logging.

**Comment by erri120** [comment] 2024-04-17 13:04
@MaggiWuerze did you log-in?

**Comment by MaggiWuerze** [comment] 2024-04-22 13:35
Yes I did

**Comment by erri120** [comment] 2024-06-12 12:09
If the issue is still relevant with the latest version, you can re-open it.

**Closed by erri120** 2024-06-12 12:09 UTC
Labels: Bug, os-linux, User Raised
