### ISSUE TITLE
Epic: Diagnostics

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1188] opened 2024-04-09 12:17 UTC
Adding a place for all diagnostics work to be linked to. 

- [x] https://github.com/Nexus-Mods/NexusMods.App/issues/1181

**Comment by Al12rs** [comment] 2024-04-09 12:18
https://github.com/Nexus-Mods/NexusMods.App/issues/327

**Comment by erri120** [comment] 2024-08-07 10:24
Duplicate of #327.

**Closed by erri120** 2024-08-07 10:24 UTC
Labels: meta-epic
