### ISSUE TITLE
Selective GameFiles Backup

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1578] opened 2024-06-11 10:08 UTC
As a user of the nexus mods app
I want to be able to decide if I use the undo feature
So that I can decide if I want the backup to use additional hard drive space

Allowing users to decide if they want to use the backup/undo feature is something that has been heard from the feedback received.  Users want to choose if the app uses additional drive space.

**Comment by Al12rs** [comment] 2024-06-12 16:25
Duplicate of #899

**Comment by Al12rs** [comment] 2024-06-12 16:27
See relevant comments from 
- #899

**Closed** 2024-07-03 12:54 UTC
Labels: Epic: Apply-ingest
