### ISSUE TITLE
Language Dropdown

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1568] opened 2024-06-10 10:44 UTC
![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/163429175/f0e2e56d-cb2c-4daa-9293-559d1b432b6d)

Please can you make sure the language names start with a capital letter.

**Comment by erri120** [comment] 2024-06-10 10:45
Duplicate of #1313.

**Closed by erri120** 2024-06-10 10:45 UTC
Labels: Design UI/UX, Dev UI
