### ISSUE TITLE
Stardew Valley - Diagnostic for SMAPI update available. 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1292] opened 2024-04-30 10:57 UTC
# User story

**As a** Stardew Valley modder

**I want to** know if there's an update for SMAPI

**So that** I can stay up to date with the latest features. 

## Requirements
_(Any other information related to but not covered by the story)_

## Design
_(Any designs required for this story)_

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** _______

**When** _______

**Then** _______

**Comment by erri120** [comment] 2024-04-30 11:00
Technically not a duplicate of #1160, but it's the same thing. Mod updates might go through diagnostics, but the update system itself won't be part of diagnostics.

**Closed by erri120** 2024-04-30 11:00 UTC
