### ISSUE TITLE
Only flag a loadout as needing to apply if changes are necessary. 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1467] opened 2024-05-28 10:33 UTC
# Improvement

## Currently 
The app will show the "Apply" button even if no changes are required to the game folder. 

## We want
Only Apply (or ask the user to apply with the button) when files or other data need to be changed. 

## Supporting Information
Example:
- Install a mod
- Apply changes
- Disable the mod
- Apply changes
- Remove the disabled mod from the loadout
- The app will show the "Apply" button again, but nothing needs to change. 

## Design
_(Any designs to required for this feature)_

**Comment by LukeNexusMods** [comment] 2024-10-28 11:27
@Pickysaurus Is this fixed now?

**Comment by Sewer56** [comment] 2024-10-29 19:34
No, it's not.

There are still times where hitting `Apply` does a no-op; we should avoid that as on Windows that may prevent users from running games multiple times at the same time (e.g. for multiplayer testing).

**Comment by Al12rs** [comment] 2024-10-30 09:55
@Sewer56 I don't think what you describe is the same as the problem reported in this ticket.
The ticket refers to Apply button being enabled and shown to users even if there is nothing to apply. I think this might be fixed.
If not, do you know steps to reproduce?

What you seem to be referring to is more "Don't perform a synchronize operation if there is nothing to apply or ingest"?

**Comment by Sewer56** [comment] 2024-10-30 10:52
> What you seem to be referring to is more "Don't perform a synchronize operation if there is nothing to apply or ingest"?

@Al12rs yeah that's what I'm referring to.
For example, if you create multiple loadouts, the others will still show both 'Apply' button and perform a 'Synchronize' on game launch. Even though the files to be deployed are exactly identical, thus the Apply action is a no-op.

**Comment by Al12rs** [comment] 2024-10-30 10:56
That makes sense though, because Syncrhonizing a Loadout sets it as the Last Applied and thus the "Active" loadout.
Even if there is nothing to do between the switch you want to show the Apply button to allow users to consciously switch from one loadout to another.

**Comment by Sewer56** [comment] 2024-10-30 11:09
I think tnis ticket is good for closing if the original repro is no longer relevant.

I was just trying to point out an edge case there, but after some more work on the code there, the UI isn't equipped to handle that edge case in any case. So it's fine for now.

**Closed** 2024-10-30 11:33 UTC
Labels: meta-improvement, Epic: Apply-ingest
