### ISSUE TITLE
GameFinder - Additional Finds

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1916] opened 2024-08-21 15:58 UTC
This work is to add to GameFinder so that it can find games in Heroic.

There are some game services that we currently dont detect. This ticket is to add the popular ones to GameFinder.

**Comment by erri120** [comment] 2024-08-21 16:00
Duplicate of https://github.com/Nexus-Mods/NexusMods.App/issues/1695.

**Closed** 2024-08-22 08:24 UTC
Labels: os-linux, Epic: Game Support
