### ISSUE TITLE
Identify solution for e2e tests on the frontend

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#221] opened 2023-03-22 15:01 UTC
## We want
We should make sure that the frontend of the app is tested automatically by e2e tests. This will reduce the need for manual testing of features or improvements on the app.

## Supporting Information
Investigate some possible solutions, on the website we use Playwright.

**Comment by halgari** [comment] 2023-03-22 15:02
Closely related to, but perhaps not a duplicate of #200

**Closed** 2023-05-10 20:33 UTC
Labels: small, spike :mag_right:
