### ISSUE TITLE
Games not showing after being added (Linux)

### ISSUE THREAD

**Issue by crosskdog** [Nexus-Mods/NexusMods.App#823] opened 2024-01-02 19:10 UTC
Games are not showing up after adding them.

I downloaded the beta hoping to mod SkyrimSE easily on my Linux distro and upon opening the launcher, signing in, and adding SkyrimSE (which I downloaded from Steam) the game wouldn'tshow up on the lleft-hand side after adding it.

The Process I followed to reproduce the bug: download the Linux version of the manager, trac , move out of the downloads folder, open the manager file. launch the .app file, sign in to nexus mods, add SkyrimSE to the manager. Upon following these steps the game would not appear in the manager even after relaunching.

This was as I understood the proper steps to follow to be able to use the manager properly and add games and use the manager as normal.

I use the Arch Linux distro known as Chimera OS, I am running it on a laptop with an Intel Core i5 10th gen with integrated graphics.

Note: I am going to transfer the SSD to another computer that can run the games but right now I have the laptop and am preparing for the transfer when I get the new computer.

**Comment by erri120** [comment] 2024-01-08 08:05
Do you have any logs that you can attach to the issue?

**Comment by ezioleq** [comment] 2024-02-13 17:30
@erri120 I can roughly reproduce this problem.

## Environment
- NexusMods.App release v0.3
- Arch Linux, 6.7.2-arch1-2
- Ryzen 7 5700X, 48 GB RAM, Radeon RX 6700 XT
- App was launched from my home directory, where the games were on another drive

## Steps
1. Open the app
2. Log in
3. Add discovered game from the main dashboard (in my case that was Cyberpunk 2077)
4. *Wait for a while* (**47 seconds**) ❌
5. The game shows up on the sidebar
6. Launcher starts to utilize 100% of the CPU copying large amounts of data to the home directory (`~/.local/share/NexusMods.App/DataModel/Archives`) ❌

## Logs
[NexusMods.App logs](https://github.com/Nexus-Mods/NexusMods.App/files/14270051/logs-cp77.txt)

**Comment by erri120** [comment] 2024-02-14 09:08
> @erri120 I can roughly reproduce this problem.
> ## Environment
> 
>     * NexusMods.App release v0.3
> 
>     * Arch Linux, 6.7.2-arch1-2
> 
>     * Ryzen 7 5700X, 48 GB RAM, Radeon RX 6700 XT
> 
>     * App was launched from my home directory, where the games were on another drive
> 
> 
> ## Steps
> 
>     1. Open the app
> 
>     2. Log in
> 
>     3. Add discovered game from the main dashboard (in my case that was Cyberpunk 2077)
> 
>     4. _Wait for a while_ (**47 seconds**) ❌
> 
>     5. The game shows up on the sidebar
> 
>     6. Launcher starts to utilize 100% of the CPU copying large amounts of data to the home directory (`~/.local/share/NexusMods.App/DataModel/Archives`) ❌
> 
> 
> ## Logs
> 
> [NexusMods.App logs](https://github.com/Nexus-Mods/NexusMods.App/files/14270051/logs-cp77.txt)

This is unrelated to the issue. Your logs don't indicate a problem. Step 4 and 6 that you marked with :x: are also intended to work that way currently.

**Comment by erri120** [comment] 2024-02-14 09:09
This issue might have been resolved in 0.3, re-open the issue if that's not the case.

**Closed by erri120** 2024-02-14 09:09 UTC
Labels: meta-bug, os-linux

**Comment by Sewer56** [comment] 2024-02-14 16:02
> @erri120 I can roughly reproduce this problem.
> ## Environment
> 
>     * NexusMods.App release v0.3
> 
>     * Arch Linux, 6.7.2-arch1-2
> 
>     * Ryzen 7 5700X, 48 GB RAM, Radeon RX 6700 XT
> 
>     * App was launched from my home directory, where the games were on another drive
> 
> 
> ## Steps
> 
>     1. Open the app
> 
>     2. Log in
> 
>     3. Add discovered game from the main dashboard (in my case that was Cyberpunk 2077)
> 
>     4. _Wait for a while_ (**47 seconds**) ❌
> 
>     5. The game shows up on the sidebar
> 
>     6. Launcher starts to utilize 100% of the CPU copying large amounts of data to the home directory (`~/.local/share/NexusMods.App/DataModel/Archives`) ❌
> 
> 
> ## Logs
> 
> [NexusMods.App logs](https://github.com/Nexus-Mods/NexusMods.App/files/14270051/logs-cp77.txt)

3. is covered by
- https://github.com/Nexus-Mods/NexusMods.App/issues/770#issue-1990850516
- https://github.com/Nexus-Mods/NexusMods.App/issues/654#issue-1903199334

The core issue is, we hash the files first, and only show the game after all the files are hashes. This might take a while if the game is big.

Say in the case of Cyberpunk (60GB), and an NVMe drive (assume average read speed of 2GiB/s), that's still 30 seconds. Ideally we let the user navigate to the game before the hashing is done, and continue in the background.

The other part is recompressing game files. We could probably special case that to use a lower compression level, since these assets are likely to be compressed well out of the box. (Unlike mods, which may be full of loose files loaded by a mod framework)
