### ISSUE TITLE
FlexPanel bug: App crashes when clicking the add panel dropdown in the top bar

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1816] opened 2024-07-29 12:32 UTC
## Steps to reproduce:
Click the add panel dropdown button in the top bar.

**Comment by Al12rs** [comment] 2024-08-05 11:58
This is caused by a bug in FlexPanel:
![image](https://github.com/user-attachments/assets/02140434-7ade-436c-adeb-5575b944949f)

This should be fixed with:
- [ ] https://github.com/AvaloniaUI/Avalonia.Labs/pull/77
But we need a new Avalonia.Labs release containing the fix

**Closed** 2024-08-06 09:54 UTC
Labels: Bug
