### ISSUE TITLE
Login Failure on Linux (Nobara 40, KDE Plasma 6.1.1 Wayland)

### ISSUE THREAD

**Issue by ItsRogueRen** [Nexus-Mods/NexusMods.App#1756] opened 2024-07-11 23:11 UTC
# Bug Report

## Summary
Unable to log in via web link. Browser opens, login goes through on the website, but the app itself cannot log in after. Browser prompts to choose an app to pen the link with but choosing the appimage does nothing and the app infinitely waits to log in. 

## Steps to reproduce
_(How one can reproduce the issue - this is very important)_
open the appimage on Linux
click log in
log in on nexusmods
when prompted by the xdg portal, choose the appimage to open the link with

## What is the expected behaviour?
_(What did you expect to happen instead?)_
App logs in to your account

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

[nexusmods.app.main.00.log](https://github.com/user-attachments/files/16184512/nexusmods.app.main.00.log)
[nexusmods.app.slim.00.log](https://github.com/user-attachments/files/16184514/nexusmods.app.slim.00.log)

I would suggest having a way to log in that doesn't require a separate web browser, just have the login page in the app itself.

**Comment by EzioTheDeadPoet** [comment] 2024-07-12 06:27
https://nexus-mods.github.io/NexusMods.App/users/faq/#linux this should cover the cause and the fix for your issue.

**Comment by ItsRogueRen** [comment] 2024-07-12 06:36
> https://nexus-mods.github.io/NexusMods.App/users/faq/#linux this should cover the cause and the fix for your issue.
> 

No it does not, I get a new tab after hitting "Authorize", a prompt to allow an app to open the link, and then nothing. 

Regardless, having it go through your browser seems needlessly complicated when I could just log in within the app itself.

**Comment by EzioTheDeadPoet** [comment] 2024-07-12 06:47
What browser are you using ?

**Comment by erri120** [comment] 2024-07-15 07:17
According to the logs, the App received the NXM command successfully.

**Comment by RodoMa92** [comment] 2024-07-15 13:56
Same issue with 0.5.3. No login works again.

**Comment by RodoMa92** [comment] 2024-07-15 13:57
> > https://nexus-mods.github.io/NexusMods.App/users/faq/#linux this should cover the cause and the fix for your issue.
> 
> No it does not, I get a new tab after hitting "Authorize", a prompt to allow an app to open the link, and then nothing.
> 
> Regardless, having it go through your browser seems needlessly complicated when I could just log in within the app itself.

Yeah, they should really leave a fallback, especially since the NexusMod site itself gives you the actual token to paste in. Not sure why it hasn't really be considered to add a box where you would be able to paste the token or even login manually directly in the app at this point.

**Comment by RodoMa92** [comment] 2024-07-15 14:06
Already found one bug: You don't update the link inside `nexusmods-app-nxm.desktop` in case the path of the AppImage changes (Like when using GearLevel, which will add a version crc for tracking versions in the AppName). But even manually updating it and pointing to the new appimage file the login still fails, so there is still another problem in the login flow.

**Comment by erri120** [comment] 2024-07-15 14:24
> Already found one bug: You don't update the link inside `nexusmods-app-nxm.desktop` in case the path of the AppImage changes (Like when using GearLevel, which will add a version crc for tracking versions in the AppName). But even manually updating it and pointing to the new appimage file the login still fails, so there is still another problem in the login flow.

You should remove previous `.desktop` files and revert manual changes. 0.5.3 creates `com.nexusmods.app.desktop` for you and sets it as the default URL scheme handler for `nxm://` links. Your browser might have some stuff cached, so try to restart your browser.

You can verify that the NXM handler is registered correctly by using `xdg-open nxm://something`.

**Comment by RodoMa92** [comment] 2024-07-15 15:27
On Firefox nothing makes it work correctly. Copy pasting the link on ungoogled chromium finally made it fire correctly. Still, you should add a fallback if logging in is so fragile.

**Comment by EzioTheDeadPoet** [comment] 2024-07-15 15:35
this is a Firefox issue most likely and the explanation and fix is in the FAQ.

**Comment by RodoMa92** [comment] 2024-07-15 15:59
> this is a Firefox issue most likely and the explanation and fix is in the FAQ.

Yep, already did. Still not working even following the FAQ, sadly.

**Comment by RodoMa92** [comment] 2024-07-15 16:09
Yep, it seems that firefox flatpak has issues with links. xdg-portal doesn't work. Switched to Librewolf and it works 100% fine. Good for me, since I was in the process of switching anyway.

**Comment by erri120** [comment] 2024-07-15 17:33
> Yep, it seems that firefox flatpak has issues with links. xdg-portal doesn't work. Switched to Librewolf and it works 100% fine. Good for me, since I was in the process of switching anyway.

That's odd, but glad you got it working.

@ItsRogueRen the issue should be fixed with the latest version. If you still have issues, you can re-open the issue.

**Closed by erri120** 2024-07-15 17:33 UTC

**Comment by ItsRogueRen** [comment] 2024-07-15 22:55
Appimage fails to open at all now, no error or anything.

This may be an appimage issue, unless it has its own built-in updater appimages are extremely annoying to update if you use a tool to add them to your app menu (vs flatpak, snaps, or a native package like deb or rpm).

**Comment by erri120** [comment] 2024-07-16 09:00
> Appimage fails to open at all now, no error or anything.

We don't have a migration process in place yet, so you need to clean your existing data.
