### ISSUE TITLE
View switching creates a new my mods entry

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2027] opened 2024-09-12 10:06 UTC
https://github.com/user-attachments/assets/22674b67-944e-455c-a5b2-a3b03cc31ea9

Switching from my games to a loadout increases the my mods pages. 

Switching between loadouts also creates a my mods page.

**Comment by erri120** [comment] 2024-09-12 10:07
Duplicate of #2022.

**Closed by erri120** 2024-09-12 10:07 UTC
Labels: Bug
