### ISSUE TITLE
Nexus Mods app cannot launch Cyberpunk2077(Linux)

### ISSUE THREAD

**Issue by Recounted34** [Nexus-Mods/NexusMods.App#2204] opened 2024-10-28 22:51 UTC
# Bug Report

## Summary
Cyberpunk 2077 does not launch when the play button is pressed. Instead it is stuck on "Running...".

## Steps to reproduce
As above

## What is the expected behaviour?
Cyberpunk 2077 launching

## Other information
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/17549450/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/17549461/nexusmods.app.slim.current.log)

Log files can be found in these locations:

- Linux: `~/.local/state/NexusMods.App/Logs`

**Comment by Recounted34** [comment] 2024-10-29 20:58
I reinstalled protontricks as a native package instead of a flatpak, and it works now. Seems to be an issue with the flatpak version of protontricks.

**Comment by Sewer56** [comment] 2024-10-29 21:40
Figures. This is a duplicate of:
- https://github.com/Nexus-Mods/NexusMods.App/issues/2094

So I'll close it in the meantime.
Will get around to it when some spare time arrives.

**Closed by Sewer56** 2024-10-29 21:40 UTC
