### ISSUE TITLE
Allow users to stop managing games

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#773] opened 2023-11-13 15:31 UTC
# Improvement

## Currently 
When you go to 'My Games' and add a game, the 'Add game' button remains even though you've added the game.

## We want
When a game is currently being managed, we should change the 'Add game' button to 'Remove game'.

The icon also needs changing from a 'plus' to something else (probably a 'minus').

## Supporting Information
![Add Game Button](https://github.com/Nexus-Mods/NexusMods.App/assets/100707075/7a5e8dce-8e85-44e7-98de-9ba84b3ebe53)

## Design
TBD

**Comment by LukeNexusMods** [comment] 2024-03-20 09:38
I believe this was confusing people when it came to deleting mods. Because they couldnt remove a game from being managed they assumed mods were not able to be deleted.

**Comment by Sewer56** [comment] 2024-03-20 09:45
I think this may change with further input from design. 

It's possible `Add Game` might change to `New Loadout` if a game already exists, some further discussion will be needed on this eventually. 

Good call, this issue got buried hard.

**Comment by Sewer56** [comment] 2024-03-20 09:45
CC @captainsandypants

**Comment by captainsandypants** [comment] 2024-03-21 12:07
The original designs cover all this, we just didn't QA.

**Comment by Al12rs** [comment] 2024-03-27 10:49
duplicate of #1106

**Comment by Al12rs** [comment] 2024-06-11 09:35
This was implemented by @Sewer56

**Closed by Al12rs** 2024-06-11 09:35 UTC
Labels: meta-improvement, Design UI/UX, Epic: Loadouts
