### ISSUE TITLE
Latest appimage version on Linux with Bazzite Kinoite 40 just crashes.

### ISSUE THREAD

**Issue by RodoMa92** [Nexus-Mods/NexusMods.App#1766] opened 2024-07-15 13:52 UTC
# Bug Report

## Summary
Launching the new version just built cause the app to just throw an exception and dies.

## Steps to reproduce
Launch the previous appimage without logging in, then try to use the new release just released. The app just dies.

## What is the expected behaviour?
The app opens fine

## Other information
```
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more hosted services failed to start. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.))
 ---> System.AggregateException: One or more hosted services failed to start. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NexusMods.StandardGameLocators.ManuallyAddedGame.FindByGameDomain(IDb db, GameDomain value) in /_/src/NexusMods.StandardGameLocators/obj/Release/net8.0/NexusMods.MnemonicDB.SourceGenerator/NexusMods.MnemonicDB.SourceGenerator.ModelGenerator/NexusMods_StandardGameLocators_ManuallyAddedGame.Generated.cs:line 39
   at NexusMods.StandardGameLocators.ManuallyAddedLocator.Find(ILocatableGame game) in /_/src/NexusMods.StandardGameLocators/ManuallyAddedLocator.cs:line 73
   at NexusMods.DataModel.GameRegistry.FindInstallations()+MoveNext() in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 136
   at System.Collections.Generic.AsyncEnumerableHelpers.ToSet[T](IAsyncEnumerable`1 source, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 108
   at System.Collections.Generic.AsyncEnumerableHelpers.ToSet[T](IAsyncEnumerable`1 source, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 108
   at System.Linq.AsyncEnumerable.DistinctAsyncIterator`1.ToArrayAsync(CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Distinct.cs:line 56
   at NexusMods.DataModel.GameRegistry.Startup(CancellationToken token) in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 69
   at NexusMods.DataModel.GameRegistry.StartAsync(CancellationToken cancellationToken) in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 151
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at NexusMods.Networking.Downloaders.Tasks.State.DownloaderState.All(IDb db) in /_/src/Networking/NexusMods.Networking.Downloaders/obj/Release/net8.0/NexusMods.MnemonicDB.SourceGenerator/NexusMods.MnemonicDB.SourceGenerator.ModelGenerator/NexusMods_Networking_Downloaders_Tasks_State_DownloaderState.Generated.cs:line 81
   at NexusMods.Networking.Downloaders.DownloadService.StartAsync(CancellationToken cancellationToken) in /_/src/Networking/NexusMods.Networking.Downloaders/DownloadService.cs:line 162
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)<---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
   at NexusMods.App.Program.Main(String[] args) in /_/src/NexusMods.App/Program.cs:line 63
```

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by Sewer56** [comment] 2024-07-15 13:53
Duplicate of
- https://github.com/Nexus-Mods/NexusMods.App/issues/1765

See linked issue for more details.

**Closed by Sewer56** 2024-07-15 13:53 UTC
