### ISSUE TITLE
Crash when adding Stardew Valley mod

### ISSUE THREAD

**Issue by BucketListMod** [Nexus-Mods/NexusMods.App#1782] opened 2024-07-17 02:46 UTC
# Bug Report

## Summary
Upon installing mods through Nexus one-by-one, 171st mod crashes app

## Steps to reproduce
1. Start clean, no mods, no SMAPI
2. Log into Nexus via app
3. Download and apply mods one-by-one via Vortex (.nxm) links
4. 171st mod crashes app
5. Attempts to re-open and re-use the app cause it to crash shortly after clicking "View" on Stardew Valley

## What is the expected behaviour?
App to continue functioning as normal

## Other information
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16258575/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/16258576/nexusmods.app.slim.current.log)

**Comment by Sewer56** [comment] 2024-07-17 02:57
This might be problematic to debug.

Would you be able to upload the other logs from the logs folder (while they're still there!!).
There's no errors in the existing logs it seems.

A dump of the database from `~/.local/share/NexusMods.App/DataModel/MnemonicDB.rocksdb` might also potentially be useful here.
From what I gather, there was an error in a previous run, and now the App's in a difficult state internally.

**Comment by BucketListMod** [comment] 2024-07-17 03:16
Zip archives for you! I also realized my cloud server may not have synced properly so that log may not have even been accurate, but everything in these zips will be!

[Logs.zip](https://github.com/user-attachments/files/16258736/Logs.zip)

MnemonicDB is too big for upload, instead is on a cloud
Link: https://use10.thegood.cloud/s/Hka7KA2onRff8Dg
Password: A1^~>]R\Ea;Mso$LbjG?@**^@

**Comment by Pickysaurus** [comment] 2024-07-17 10:55
Do you happen to know what the 171st mod you added was?

**Comment by erri120** [comment] 2024-07-17 11:06
Duplicate of #1783.

```
01:14:57.118 [ERROR] (NexusMods.App.Program) Encountered an exception published to an object with an unobserved ThrownExceptions property|System.AggregateException: One or more errors occurred. (A positive capacity must be specified for a Memory Mapped File backed by an empty file.) (A positive capacity must be specified for a Memory Mapped File backed by an empty file.)
 ---> System.ArgumentException: A positive capacity must be specified for a Memory Mapped File backed by an empty file.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access)
   at NexusMods.Archives.Nx.FileProviders.OutputFileProvider..ctor(String outputFolder, String relativePath, FileEntry entry)
   at NexusMods.DataModel.NxFileStore.<>c__DisplayClass7_1.<ExtractFiles>b__2(Int32 x) in /_/src/NexusMods.DataModel/NxFileStore.cs:line 182
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.ArgumentException: A positive capacity must be specified for a Memory Mapped File backed by an empty file.
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access)
   at NexusMods.Archives.Nx.FileProviders.OutputFileProvider..ctor(String outputFolder, String relativePath, FileEntry entry)
   at NexusMods.DataModel.NxFileStore.<>c__DisplayClass7_1.<ExtractFiles>b__2(Int32 x) in /_/src/NexusMods.DataModel/NxFileStore.cs:line 182
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`2.<ForWorker>b__1(RangeWorker& currentWorker, Int64 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

**Closed by erri120** 2024-07-17 11:06 UTC
Labels: Bug

**Comment by BucketListMod** [comment] 2024-07-17 14:26
Ah, I see! Do you still need to know which mid it was, or does that not matter now that it's been identified?

**Comment by Pickysaurus** [comment] 2024-07-18 06:52
> Ah, I see! Do you still need to know which mod it was, or does that not matter now that it's been identified? (My apologies for late response as well, fell asleep)

Unfortunately, the log file doesn't do a great job of telling us which mod it relates to specifically. If you sort by install time and remove the newer ones until the "Apply" option works without crashing that would be the best way to work it out.
