### ISSUE TITLE
Play Button text stuck on "Running..."

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1950] opened 2024-08-28 12:42 UTC
![Image](https://github.com/user-attachments/assets/ddcba756-b4a3-41b0-835b-19df83d68889)

After quitting Cyberpunk sometimes the play button turns into this.

It becomes clickable at this point but the running text doesn't change to Play

**Comment by LukeNexusMods** [comment] 2024-08-29 12:31
This also happening when applying loadouts

**Comment by Sewer56** [comment] 2024-10-24 09:24
Duplicate of: https://github.com/Nexus-Mods/NexusMods.App/issues/759

**Closed** 2024-10-28 11:16 UTC
Labels: Bug, weight-1
