### ISSUE TITLE
Log in to download mod

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1482] opened 2024-05-29 08:07 UTC
Currently the app requires a user to log in to be able to download a mod from Nexus Mods. There is no direction for the user here and it does not prevent them from downloading mods if they are not logged in. 

When downloading mods without being logged in the mods are added to the app but in a state where they cannot be used. 

Users should be logged in to download mods, the app should have some direction for this before sending them to the website.

**Comment by LukeNexusMods** [comment] 2024-05-29 08:08
@captainsandypants Do you have any recommendations for this please?

**Comment by Al12rs** [comment] 2024-05-29 08:14
duplicate of #760

**Closed by Al12rs** 2024-05-29 08:14 UTC
