### ISSUE TITLE
Apply Diff Preview Changes page infinite spinner on refresh

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1498] opened 2024-05-30 09:28 UTC
# Bug Report

## Summary
The first time you click refresh on a preview changes page you get a never ending spinner:

https://github.com/Nexus-Mods/NexusMods.App/assets/163429175/4ebf4263-5a7e-485f-8bbb-f935fd8444c2

**Comment by Al12rs** [comment] 2024-05-30 09:58
I managed to reproduce once, then when I went to debug it I couldn't reproduce anymore

**Comment by LukeNexusMods** [comment] 2024-05-30 10:01
[nexusmods.app.main.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15497194/nexusmods.app.main.current.log)

**Comment by Al12rs** [comment] 2024-05-30 16:25
Hopefully fixed in #1502

**Closed by Al12rs** 2024-05-30 16:25 UTC
Labels: meta-bug
