### ISSUE TITLE
Bug: Padding Between entries in My Games is Missing

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#1604] opened 2024-06-12 13:15 UTC
# Bug Report

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/ad5ef2e7-0ce2-413a-a84b-9a4ca4d65632)

I don't think this needs additional explanation.
Go to Figma, and match it up.

**Comment by erri120** [comment] 2024-06-12 13:18
Probably a duplicate of #1601 and probably already done in #1602.

**Comment by Al12rs** [comment] 2024-06-12 13:18
Yeah this is fixed in #1602

**Closed by erri120** 2024-06-12 13:18 UTC
Labels: Bug, Dev UI
